provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  pointinpolygon:
    lang: golang-middleware
    handler: ./pointinpolygon
    image: michaelvlaar/pointinpolygon:latest
    environment:
      content_type: application/json
